### ISSUE TITLE
add config file option instead of parsing cmd line args

### ISSUE THREAD

**Issue by aegidel** [wosc/schlund-ddns#1]
FIXME: Please don't take password from cmd line arg (ps/ proc/ history vulnerability).
better: ~/.schlund-ddns with config && parse args for rest / adjustments.

Also: small typo in readme. Should probably be "schlund-ddns --help" instead of "ddns-update --help" under Usage section.

Sorry for not providing a pull request, i've looked at a quick fix for passing PASS via config file but this uses gocept.logging.ArgumentParser() that I'm not familiar with.

Thanks for the handy schlund-ddns updater!

**Comment by wosc** [comment]
Sorry I'm so very late to this, version 1.3 now contains this feature.
