### ISSUE TITLE
Fix zone requests with a.b.c.example.tld type domains

### ISSUE THREAD

**Issue by aegidel** [wosc/schlund-ddns#2]
Problem:

host and domain are split at first occurence of splt_char in update.py resulting in a wrong zone domain for sub-levelled subdomains (e.g. a.b.example.tld is split in "a","b.example.tld", therefore an error is raised because of zone not found).

proposed quick fix:

```
$ diff /usr/local/lib/python3.7/site-packages/ws/ddns/update.py ./update.py 
60c60,62
<         host, domain = hostname.split('.', 1)
---
>         tmp = hostname.split('.')
>         domain = '.'.join(tmp[2:])
>         host = hostname.replace('.'+domain,'')

```

there will be a cleaner fix for this I guess, which is why i don't submit a pull request.

Again, thank you for creating the great package!

**Comment by wosc** [comment]
Sorry I'm so very late to this, version 1.3 fixes this.
